#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyNhaHang")]
	public partial class QL_NhaHangDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETDONHANGONLINE(CHITIETDONHANGONLINE instance);
    partial void UpdateCHITIETDONHANGONLINE(CHITIETDONHANGONLINE instance);
    partial void DeleteCHITIETDONHANGONLINE(CHITIETDONHANGONLINE instance);
    partial void InsertVOUCHER(VOUCHER instance);
    partial void UpdateVOUCHER(VOUCHER instance);
    partial void DeleteVOUCHER(VOUCHER instance);
    partial void InsertCHITIETDONNHAPHANG(CHITIETDONNHAPHANG instance);
    partial void UpdateCHITIETDONNHAPHANG(CHITIETDONNHAPHANG instance);
    partial void DeleteCHITIETDONNHAPHANG(CHITIETDONNHAPHANG instance);
    partial void InsertCHITIETHOADON(CHITIETHOADON instance);
    partial void UpdateCHITIETHOADON(CHITIETHOADON instance);
    partial void DeleteCHITIETHOADON(CHITIETHOADON instance);
    partial void InsertDINHLUONG(DINHLUONG instance);
    partial void UpdateDINHLUONG(DINHLUONG instance);
    partial void DeleteDINHLUONG(DINHLUONG instance);
    partial void InsertDONHANGONLINE(DONHANGONLINE instance);
    partial void UpdateDONHANGONLINE(DONHANGONLINE instance);
    partial void DeleteDONHANGONLINE(DONHANGONLINE instance);
    partial void InsertDONNHAPHANG(DONNHAPHANG instance);
    partial void UpdateDONNHAPHANG(DONNHAPHANG instance);
    partial void DeleteDONNHAPHANG(DONNHAPHANG instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHOILUONG(KHOILUONG instance);
    partial void UpdateKHOILUONG(KHOILUONG instance);
    partial void DeleteKHOILUONG(KHOILUONG instance);
    partial void InsertLOAI(LOAI instance);
    partial void UpdateLOAI(LOAI instance);
    partial void DeleteLOAI(LOAI instance);
    partial void InsertMENU(MENU instance);
    partial void UpdateMENU(MENU instance);
    partial void DeleteMENU(MENU instance);
    partial void InsertNGUYENLIEU(NGUYENLIEU instance);
    partial void UpdateNGUYENLIEU(NGUYENLIEU instance);
    partial void DeleteNGUYENLIEU(NGUYENLIEU instance);
    partial void InsertNGUYENLIEULAMMON(NGUYENLIEULAMMON instance);
    partial void UpdateNGUYENLIEULAMMON(NGUYENLIEULAMMON instance);
    partial void DeleteNGUYENLIEULAMMON(NGUYENLIEULAMMON instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHANQUYEN(PHANQUYEN instance);
    partial void UpdatePHANQUYEN(PHANQUYEN instance);
    partial void DeletePHANQUYEN(PHANQUYEN instance);
    #endregion
		
		public QL_NhaHangDataContext() : 
				base(global::DAL.Properties.Settings.Default.QL_NHAHANGConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_NhaHangDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_NhaHangDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_NhaHangDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_NhaHangDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETDONHANGONLINE> CHITIETDONHANGONLINEs
		{
			get
			{
				return this.GetTable<CHITIETDONHANGONLINE>();
			}
		}
		
		public System.Data.Linq.Table<VOUCHER> VOUCHERs
		{
			get
			{
				return this.GetTable<VOUCHER>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETDONNHAPHANG> CHITIETDONNHAPHANGs
		{
			get
			{
				return this.GetTable<CHITIETDONNHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOADON> CHITIETHOADONs
		{
			get
			{
				return this.GetTable<CHITIETHOADON>();
			}
		}
		
		public System.Data.Linq.Table<DINHLUONG> DINHLUONGs
		{
			get
			{
				return this.GetTable<DINHLUONG>();
			}
		}
		
		public System.Data.Linq.Table<DONHANGONLINE> DONHANGONLINEs
		{
			get
			{
				return this.GetTable<DONHANGONLINE>();
			}
		}
		
		public System.Data.Linq.Table<DONNHAPHANG> DONNHAPHANGs
		{
			get
			{
				return this.GetTable<DONNHAPHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHOILUONG> KHOILUONGs
		{
			get
			{
				return this.GetTable<KHOILUONG>();
			}
		}
		
		public System.Data.Linq.Table<LOAI> LOAIs
		{
			get
			{
				return this.GetTable<LOAI>();
			}
		}
		
		public System.Data.Linq.Table<MENU> MENUs
		{
			get
			{
				return this.GetTable<MENU>();
			}
		}
		
		public System.Data.Linq.Table<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this.GetTable<NGUYENLIEU>();
			}
		}
		
		public System.Data.Linq.Table<NGUYENLIEULAMMON> NGUYENLIEULAMMONs
		{
			get
			{
				return this.GetTable<NGUYENLIEULAMMON>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONHANGONLINE")]
	public partial class CHITIETDONHANGONLINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dho;
		
		private int _id_mon;
		
		private System.Nullable<int> _sl;
		
		private System.Nullable<int> _thanhtien;
		
		private System.Nullable<int> _giaban;
		
		private EntityRef<DONHANGONLINE> _DONHANGONLINE;
		
		private EntityRef<MENU> _MENU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dhoChanging(int value);
    partial void Onid_dhoChanged();
    partial void Onid_monChanging(int value);
    partial void Onid_monChanged();
    partial void OnslChanging(System.Nullable<int> value);
    partial void OnslChanged();
    partial void OnthanhtienChanging(System.Nullable<int> value);
    partial void OnthanhtienChanged();
    partial void OngiabanChanging(System.Nullable<int> value);
    partial void OngiabanChanged();
    #endregion
		
		public CHITIETDONHANGONLINE()
		{
			this._DONHANGONLINE = default(EntityRef<DONHANGONLINE>);
			this._MENU = default(EntityRef<MENU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dho", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_dho
		{
			get
			{
				return this._id_dho;
			}
			set
			{
				if ((this._id_dho != value))
				{
					if (this._DONHANGONLINE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dhoChanging(value);
					this.SendPropertyChanging();
					this._id_dho = value;
					this.SendPropertyChanged("id_dho");
					this.Onid_dhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_mon
		{
			get
			{
				return this._id_mon;
			}
			set
			{
				if ((this._id_mon != value))
				{
					if (this._MENU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_monChanging(value);
					this.SendPropertyChanging();
					this._id_mon = value;
					this.SendPropertyChanged("id_mon");
					this.Onid_monChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl", DbType="Int")]
		public System.Nullable<int> sl
		{
			get
			{
				return this._sl;
			}
			set
			{
				if ((this._sl != value))
				{
					this.OnslChanging(value);
					this.SendPropertyChanging();
					this._sl = value;
					this.SendPropertyChanged("sl");
					this.OnslChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Int")]
		public System.Nullable<int> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaban", DbType="Int")]
		public System.Nullable<int> giaban
		{
			get
			{
				return this._giaban;
			}
			set
			{
				if ((this._giaban != value))
				{
					this.OngiabanChanging(value);
					this.SendPropertyChanging();
					this._giaban = value;
					this.SendPropertyChanged("giaban");
					this.OngiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANGONLINE_CHITIETDONHANGONLINE", Storage="_DONHANGONLINE", ThisKey="id_dho", OtherKey="id_dho", IsForeignKey=true)]
		public DONHANGONLINE DONHANGONLINE
		{
			get
			{
				return this._DONHANGONLINE.Entity;
			}
			set
			{
				DONHANGONLINE previousValue = this._DONHANGONLINE.Entity;
				if (((previousValue != value) 
							|| (this._DONHANGONLINE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONHANGONLINE.Entity = null;
						previousValue.CHITIETDONHANGONLINEs.Remove(this);
					}
					this._DONHANGONLINE.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGONLINEs.Add(this);
						this._id_dho = value.id_dho;
					}
					else
					{
						this._id_dho = default(int);
					}
					this.SendPropertyChanged("DONHANGONLINE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_CHITIETDONHANGONLINE", Storage="_MENU", ThisKey="id_mon", OtherKey="id_mon", IsForeignKey=true)]
		public MENU MENU
		{
			get
			{
				return this._MENU.Entity;
			}
			set
			{
				MENU previousValue = this._MENU.Entity;
				if (((previousValue != value) 
							|| (this._MENU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MENU.Entity = null;
						previousValue.CHITIETDONHANGONLINEs.Remove(this);
					}
					this._MENU.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONHANGONLINEs.Add(this);
						this._id_mon = value.id_mon;
					}
					else
					{
						this._id_mon = default(int);
					}
					this.SendPropertyChanged("MENU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VOUCHER")]
	public partial class VOUCHER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_voucher;
		
		private System.Nullable<System.DateTime> _ngaybatdau;
		
		private System.Nullable<System.DateTime> _ngayhethan;
		
		private string _mucgiam;
		
		private System.Nullable<int> _yeucau;
		
		private string _tenvoucher;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_voucherChanging(int value);
    partial void Onid_voucherChanged();
    partial void OnngaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnngaybatdauChanged();
    partial void OnngayhethanChanging(System.Nullable<System.DateTime> value);
    partial void OnngayhethanChanged();
    partial void OnmucgiamChanging(string value);
    partial void OnmucgiamChanged();
    partial void OnyeucauChanging(System.Nullable<int> value);
    partial void OnyeucauChanged();
    partial void OntenvoucherChanging(string value);
    partial void OntenvoucherChanged();
    #endregion
		
		public VOUCHER()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_voucher", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_voucher
		{
			get
			{
				return this._id_voucher;
			}
			set
			{
				if ((this._id_voucher != value))
				{
					this.Onid_voucherChanging(value);
					this.SendPropertyChanging();
					this._id_voucher = value;
					this.SendPropertyChanged("id_voucher");
					this.Onid_voucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaybatdau", DbType="Date")]
		public System.Nullable<System.DateTime> ngaybatdau
		{
			get
			{
				return this._ngaybatdau;
			}
			set
			{
				if ((this._ngaybatdau != value))
				{
					this.OnngaybatdauChanging(value);
					this.SendPropertyChanging();
					this._ngaybatdau = value;
					this.SendPropertyChanged("ngaybatdau");
					this.OnngaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayhethan", DbType="Date")]
		public System.Nullable<System.DateTime> ngayhethan
		{
			get
			{
				return this._ngayhethan;
			}
			set
			{
				if ((this._ngayhethan != value))
				{
					this.OnngayhethanChanging(value);
					this.SendPropertyChanging();
					this._ngayhethan = value;
					this.SendPropertyChanged("ngayhethan");
					this.OnngayhethanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucgiam", DbType="VarChar(5)")]
		public string mucgiam
		{
			get
			{
				return this._mucgiam;
			}
			set
			{
				if ((this._mucgiam != value))
				{
					this.OnmucgiamChanging(value);
					this.SendPropertyChanging();
					this._mucgiam = value;
					this.SendPropertyChanged("mucgiam");
					this.OnmucgiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeucau", DbType="Int")]
		public System.Nullable<int> yeucau
		{
			get
			{
				return this._yeucau;
			}
			set
			{
				if ((this._yeucau != value))
				{
					this.OnyeucauChanging(value);
					this.SendPropertyChanging();
					this._yeucau = value;
					this.SendPropertyChanged("yeucau");
					this.OnyeucauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvoucher", DbType="VarChar(20)")]
		public string tenvoucher
		{
			get
			{
				return this._tenvoucher;
			}
			set
			{
				if ((this._tenvoucher != value))
				{
					this.OntenvoucherChanging(value);
					this.SendPropertyChanging();
					this._tenvoucher = value;
					this.SendPropertyChanged("tenvoucher");
					this.OntenvoucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VOUCHER_HOADON", Storage="_HOADONs", ThisKey="id_voucher", OtherKey="id_voucher")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.VOUCHER = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.VOUCHER = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETDONNHAPHANG")]
	public partial class CHITIETDONNHAPHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nguyenlieu;
		
		private int _id_dnh;
		
		private System.Nullable<int> _khoiluongnhap;
		
		private EntityRef<DONNHAPHANG> _DONNHAPHANG;
		
		private EntityRef<NGUYENLIEU> _NGUYENLIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nguyenlieuChanging(int value);
    partial void Onid_nguyenlieuChanged();
    partial void Onid_dnhChanging(int value);
    partial void Onid_dnhChanged();
    partial void OnkhoiluongnhapChanging(System.Nullable<int> value);
    partial void OnkhoiluongnhapChanged();
    #endregion
		
		public CHITIETDONNHAPHANG()
		{
			this._DONNHAPHANG = default(EntityRef<DONNHAPHANG>);
			this._NGUYENLIEU = default(EntityRef<NGUYENLIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguyenlieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nguyenlieu
		{
			get
			{
				return this._id_nguyenlieu;
			}
			set
			{
				if ((this._id_nguyenlieu != value))
				{
					if (this._NGUYENLIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._id_nguyenlieu = value;
					this.SendPropertyChanged("id_nguyenlieu");
					this.Onid_nguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dnh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_dnh
		{
			get
			{
				return this._id_dnh;
			}
			set
			{
				if ((this._id_dnh != value))
				{
					if (this._DONNHAPHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dnhChanging(value);
					this.SendPropertyChanging();
					this._id_dnh = value;
					this.SendPropertyChanged("id_dnh");
					this.Onid_dnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiluongnhap", DbType="Int")]
		public System.Nullable<int> khoiluongnhap
		{
			get
			{
				return this._khoiluongnhap;
			}
			set
			{
				if ((this._khoiluongnhap != value))
				{
					this.OnkhoiluongnhapChanging(value);
					this.SendPropertyChanging();
					this._khoiluongnhap = value;
					this.SendPropertyChanged("khoiluongnhap");
					this.OnkhoiluongnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONNHAPHANG_CHITIETDONNHAPHANG", Storage="_DONNHAPHANG", ThisKey="id_dnh", OtherKey="id_dnh", IsForeignKey=true)]
		public DONNHAPHANG DONNHAPHANG
		{
			get
			{
				return this._DONNHAPHANG.Entity;
			}
			set
			{
				DONNHAPHANG previousValue = this._DONNHAPHANG.Entity;
				if (((previousValue != value) 
							|| (this._DONNHAPHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONNHAPHANG.Entity = null;
						previousValue.CHITIETDONNHAPHANGs.Remove(this);
					}
					this._DONNHAPHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONNHAPHANGs.Add(this);
						this._id_dnh = value.id_dnh;
					}
					else
					{
						this._id_dnh = default(int);
					}
					this.SendPropertyChanged("DONNHAPHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_CHITIETDONNHAPHANG", Storage="_NGUYENLIEU", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu", IsForeignKey=true)]
		public NGUYENLIEU NGUYENLIEU
		{
			get
			{
				return this._NGUYENLIEU.Entity;
			}
			set
			{
				NGUYENLIEU previousValue = this._NGUYENLIEU.Entity;
				if (((previousValue != value) 
							|| (this._NGUYENLIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUYENLIEU.Entity = null;
						previousValue.CHITIETDONNHAPHANGs.Remove(this);
					}
					this._NGUYENLIEU.Entity = value;
					if ((value != null))
					{
						value.CHITIETDONNHAPHANGs.Add(this);
						this._id_nguyenlieu = value.id_nguyenlieu;
					}
					else
					{
						this._id_nguyenlieu = default(int);
					}
					this.SendPropertyChanged("NGUYENLIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADON")]
	public partial class CHITIETHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hd;
		
		private int _id_mon;
		
		private System.Nullable<int> _soluong;
		
		private System.Nullable<int> _thanhtien;
		
		private System.Nullable<int> _giaban;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<MENU> _MENU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hdChanging(int value);
    partial void Onid_hdChanged();
    partial void Onid_monChanging(int value);
    partial void Onid_monChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnthanhtienChanging(System.Nullable<int> value);
    partial void OnthanhtienChanged();
    partial void OngiabanChanging(System.Nullable<int> value);
    partial void OngiabanChanged();
    #endregion
		
		public CHITIETHOADON()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._MENU = default(EntityRef<MENU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hd", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hd
		{
			get
			{
				return this._id_hd;
			}
			set
			{
				if ((this._id_hd != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hdChanging(value);
					this.SendPropertyChanging();
					this._id_hd = value;
					this.SendPropertyChanged("id_hd");
					this.Onid_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_mon
		{
			get
			{
				return this._id_mon;
			}
			set
			{
				if ((this._id_mon != value))
				{
					if (this._MENU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_monChanging(value);
					this.SendPropertyChanging();
					this._id_mon = value;
					this.SendPropertyChanged("id_mon");
					this.Onid_monChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Int")]
		public System.Nullable<int> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaban", DbType="Int")]
		public System.Nullable<int> giaban
		{
			get
			{
				return this._giaban;
			}
			set
			{
				if ((this._giaban != value))
				{
					this.OngiabanChanging(value);
					this.SendPropertyChanging();
					this._giaban = value;
					this.SendPropertyChanged("giaban");
					this.OngiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHOADON", Storage="_HOADON", ThisKey="id_hd", OtherKey="id_hd", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CHITIETHOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONs.Add(this);
						this._id_hd = value.id_hd;
					}
					else
					{
						this._id_hd = default(int);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_CHITIETHOADON", Storage="_MENU", ThisKey="id_mon", OtherKey="id_mon", IsForeignKey=true)]
		public MENU MENU
		{
			get
			{
				return this._MENU.Entity;
			}
			set
			{
				MENU previousValue = this._MENU.Entity;
				if (((previousValue != value) 
							|| (this._MENU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MENU.Entity = null;
						previousValue.CHITIETHOADONs.Remove(this);
					}
					this._MENU.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONs.Add(this);
						this._id_mon = value.id_mon;
					}
					else
					{
						this._id_mon = default(int);
					}
					this.SendPropertyChanged("MENU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DINHLUONG")]
	public partial class DINHLUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kl;
		
		private int _id_nguyenlieu;
		
		private EntityRef<KHOILUONG> _KHOILUONG;
		
		private EntityRef<NGUYENLIEU> _NGUYENLIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klChanging(int value);
    partial void Onid_klChanged();
    partial void Onid_nguyenlieuChanging(int value);
    partial void Onid_nguyenlieuChanged();
    #endregion
		
		public DINHLUONG()
		{
			this._KHOILUONG = default(EntityRef<KHOILUONG>);
			this._NGUYENLIEU = default(EntityRef<NGUYENLIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kl", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_kl
		{
			get
			{
				return this._id_kl;
			}
			set
			{
				if ((this._id_kl != value))
				{
					if (this._KHOILUONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_klChanging(value);
					this.SendPropertyChanging();
					this._id_kl = value;
					this.SendPropertyChanged("id_kl");
					this.Onid_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguyenlieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nguyenlieu
		{
			get
			{
				return this._id_nguyenlieu;
			}
			set
			{
				if ((this._id_nguyenlieu != value))
				{
					if (this._NGUYENLIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._id_nguyenlieu = value;
					this.SendPropertyChanged("id_nguyenlieu");
					this.Onid_nguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOILUONG_DINHLUONG", Storage="_KHOILUONG", ThisKey="id_kl", OtherKey="id_kl", IsForeignKey=true)]
		public KHOILUONG KHOILUONG
		{
			get
			{
				return this._KHOILUONG.Entity;
			}
			set
			{
				KHOILUONG previousValue = this._KHOILUONG.Entity;
				if (((previousValue != value) 
							|| (this._KHOILUONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOILUONG.Entity = null;
						previousValue.DINHLUONGs.Remove(this);
					}
					this._KHOILUONG.Entity = value;
					if ((value != null))
					{
						value.DINHLUONGs.Add(this);
						this._id_kl = value.id_kl;
					}
					else
					{
						this._id_kl = default(int);
					}
					this.SendPropertyChanged("KHOILUONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_DINHLUONG", Storage="_NGUYENLIEU", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu", IsForeignKey=true)]
		public NGUYENLIEU NGUYENLIEU
		{
			get
			{
				return this._NGUYENLIEU.Entity;
			}
			set
			{
				NGUYENLIEU previousValue = this._NGUYENLIEU.Entity;
				if (((previousValue != value) 
							|| (this._NGUYENLIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUYENLIEU.Entity = null;
						previousValue.DINHLUONGs.Remove(this);
					}
					this._NGUYENLIEU.Entity = value;
					if ((value != null))
					{
						value.DINHLUONGs.Add(this);
						this._id_nguyenlieu = value.id_nguyenlieu;
					}
					else
					{
						this._id_nguyenlieu = default(int);
					}
					this.SendPropertyChanged("NGUYENLIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONHANGONLINE")]
	public partial class DONHANGONLINE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dho;
		
		private System.Nullable<System.DateTime> _ngaydat;
		
		private string _diachi;
		
		private string _hoten;
		
		private string _sdt;
		
		private System.Nullable<int> _tongtien;
		
		private string _phuongthucthanhtoan;
		
		private System.Nullable<int> _tinhtranghoadon;
		
		private EntitySet<CHITIETDONHANGONLINE> _CHITIETDONHANGONLINEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dhoChanging(int value);
    partial void Onid_dhoChanged();
    partial void OnngaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydatChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OntongtienChanging(System.Nullable<int> value);
    partial void OntongtienChanged();
    partial void OnphuongthucthanhtoanChanging(string value);
    partial void OnphuongthucthanhtoanChanged();
    partial void OntinhtranghoadonChanging(System.Nullable<int> value);
    partial void OntinhtranghoadonChanged();
    #endregion
		
		public DONHANGONLINE()
		{
			this._CHITIETDONHANGONLINEs = new EntitySet<CHITIETDONHANGONLINE>(new Action<CHITIETDONHANGONLINE>(this.attach_CHITIETDONHANGONLINEs), new Action<CHITIETDONHANGONLINE>(this.detach_CHITIETDONHANGONLINEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dho", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dho
		{
			get
			{
				return this._id_dho;
			}
			set
			{
				if ((this._id_dho != value))
				{
					this.Onid_dhoChanging(value);
					this.SendPropertyChanging();
					this._id_dho = value;
					this.SendPropertyChanged("id_dho");
					this.Onid_dhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydat", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydat
		{
			get
			{
				return this._ngaydat;
			}
			set
			{
				if ((this._ngaydat != value))
				{
					this.OnngaydatChanging(value);
					this.SendPropertyChanging();
					this._ngaydat = value;
					this.SendPropertyChanged("ngaydat");
					this.OnngaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(50)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Int")]
		public System.Nullable<int> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuongthucthanhtoan", DbType="NVarChar(50)")]
		public string phuongthucthanhtoan
		{
			get
			{
				return this._phuongthucthanhtoan;
			}
			set
			{
				if ((this._phuongthucthanhtoan != value))
				{
					this.OnphuongthucthanhtoanChanging(value);
					this.SendPropertyChanging();
					this._phuongthucthanhtoan = value;
					this.SendPropertyChanged("phuongthucthanhtoan");
					this.OnphuongthucthanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtranghoadon", DbType="Int")]
		public System.Nullable<int> tinhtranghoadon
		{
			get
			{
				return this._tinhtranghoadon;
			}
			set
			{
				if ((this._tinhtranghoadon != value))
				{
					this.OntinhtranghoadonChanging(value);
					this.SendPropertyChanging();
					this._tinhtranghoadon = value;
					this.SendPropertyChanged("tinhtranghoadon");
					this.OntinhtranghoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONHANGONLINE_CHITIETDONHANGONLINE", Storage="_CHITIETDONHANGONLINEs", ThisKey="id_dho", OtherKey="id_dho")]
		public EntitySet<CHITIETDONHANGONLINE> CHITIETDONHANGONLINEs
		{
			get
			{
				return this._CHITIETDONHANGONLINEs;
			}
			set
			{
				this._CHITIETDONHANGONLINEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGONLINEs(CHITIETDONHANGONLINE entity)
		{
			this.SendPropertyChanging();
			entity.DONHANGONLINE = this;
		}
		
		private void detach_CHITIETDONHANGONLINEs(CHITIETDONHANGONLINE entity)
		{
			this.SendPropertyChanging();
			entity.DONHANGONLINE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONNHAPHANG")]
	public partial class DONNHAPHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dnh;
		
		private int _id_ncc;
		
		private System.Nullable<System.DateTime> _ngaynhap;
		
		private System.Nullable<bool> _tinhtrangnhanhang;
		
		private System.Nullable<int> _tongtien;
		
		private EntitySet<CHITIETDONNHAPHANG> _CHITIETDONNHAPHANGs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dnhChanging(int value);
    partial void Onid_dnhChanged();
    partial void Onid_nccChanging(int value);
    partial void Onid_nccChanged();
    partial void OnngaynhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaynhapChanged();
    partial void OntinhtrangnhanhangChanging(System.Nullable<bool> value);
    partial void OntinhtrangnhanhangChanged();
    partial void OntongtienChanging(System.Nullable<int> value);
    partial void OntongtienChanged();
    #endregion
		
		public DONNHAPHANG()
		{
			this._CHITIETDONNHAPHANGs = new EntitySet<CHITIETDONNHAPHANG>(new Action<CHITIETDONNHAPHANG>(this.attach_CHITIETDONNHAPHANGs), new Action<CHITIETDONNHAPHANG>(this.detach_CHITIETDONNHAPHANGs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dnh
		{
			get
			{
				return this._id_dnh;
			}
			set
			{
				if ((this._id_dnh != value))
				{
					this.Onid_dnhChanging(value);
					this.SendPropertyChanging();
					this._id_dnh = value;
					this.SendPropertyChanged("id_dnh");
					this.Onid_dnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ncc", DbType="Int NOT NULL")]
		public int id_ncc
		{
			get
			{
				return this._id_ncc;
			}
			set
			{
				if ((this._id_ncc != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nccChanging(value);
					this.SendPropertyChanging();
					this._id_ncc = value;
					this.SendPropertyChanged("id_ncc");
					this.Onid_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaynhap
		{
			get
			{
				return this._ngaynhap;
			}
			set
			{
				if ((this._ngaynhap != value))
				{
					this.OnngaynhapChanging(value);
					this.SendPropertyChanging();
					this._ngaynhap = value;
					this.SendPropertyChanged("ngaynhap");
					this.OnngaynhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrangnhanhang", DbType="Bit")]
		public System.Nullable<bool> tinhtrangnhanhang
		{
			get
			{
				return this._tinhtrangnhanhang;
			}
			set
			{
				if ((this._tinhtrangnhanhang != value))
				{
					this.OntinhtrangnhanhangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrangnhanhang = value;
					this.SendPropertyChanged("tinhtrangnhanhang");
					this.OntinhtrangnhanhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Int")]
		public System.Nullable<int> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONNHAPHANG_CHITIETDONNHAPHANG", Storage="_CHITIETDONNHAPHANGs", ThisKey="id_dnh", OtherKey="id_dnh")]
		public EntitySet<CHITIETDONNHAPHANG> CHITIETDONNHAPHANGs
		{
			get
			{
				return this._CHITIETDONNHAPHANGs;
			}
			set
			{
				this._CHITIETDONNHAPHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_DONNHAPHANG", Storage="_NHACUNGCAP", ThisKey="id_ncc", OtherKey="id_ncc", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.DONNHAPHANGs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.DONNHAPHANGs.Add(this);
						this._id_ncc = value.id_ncc;
					}
					else
					{
						this._id_ncc = default(int);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONNHAPHANGs(CHITIETDONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONNHAPHANG = this;
		}
		
		private void detach_CHITIETDONNHAPHANGs(CHITIETDONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.DONNHAPHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hd;
		
		private System.Nullable<int> _id_voucher;
		
		private int _id_nv;
		
		private System.Nullable<System.DateTime> _ngayxuat;
		
		private System.Nullable<int> _tongtien;
		
		private string _ghichu;
		
		private EntitySet<CHITIETHOADON> _CHITIETHOADONs;
		
		private EntityRef<VOUCHER> _VOUCHER;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hdChanging(int value);
    partial void Onid_hdChanged();
    partial void Onid_voucherChanging(System.Nullable<int> value);
    partial void Onid_voucherChanged();
    partial void Onid_nvChanging(int value);
    partial void Onid_nvChanged();
    partial void OnngayxuatChanging(System.Nullable<System.DateTime> value);
    partial void OnngayxuatChanged();
    partial void OntongtienChanging(System.Nullable<int> value);
    partial void OntongtienChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public HOADON()
		{
			this._CHITIETHOADONs = new EntitySet<CHITIETHOADON>(new Action<CHITIETHOADON>(this.attach_CHITIETHOADONs), new Action<CHITIETHOADON>(this.detach_CHITIETHOADONs));
			this._VOUCHER = default(EntityRef<VOUCHER>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hd
		{
			get
			{
				return this._id_hd;
			}
			set
			{
				if ((this._id_hd != value))
				{
					this.Onid_hdChanging(value);
					this.SendPropertyChanging();
					this._id_hd = value;
					this.SendPropertyChanged("id_hd");
					this.Onid_hdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_voucher", DbType="Int")]
		public System.Nullable<int> id_voucher
		{
			get
			{
				return this._id_voucher;
			}
			set
			{
				if ((this._id_voucher != value))
				{
					if (this._VOUCHER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_voucherChanging(value);
					this.SendPropertyChanging();
					this._id_voucher = value;
					this.SendPropertyChanged("id_voucher");
					this.Onid_voucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nv", DbType="Int NOT NULL")]
		public int id_nv
		{
			get
			{
				return this._id_nv;
			}
			set
			{
				if ((this._id_nv != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nvChanging(value);
					this.SendPropertyChanging();
					this._id_nv = value;
					this.SendPropertyChanged("id_nv");
					this.Onid_nvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayxuat", DbType="Date")]
		public System.Nullable<System.DateTime> ngayxuat
		{
			get
			{
				return this._ngayxuat;
			}
			set
			{
				if ((this._ngayxuat != value))
				{
					this.OnngayxuatChanging(value);
					this.SendPropertyChanging();
					this._ngayxuat = value;
					this.SendPropertyChanged("ngayxuat");
					this.OnngayxuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Int")]
		public System.Nullable<int> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(100)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIETHOADON", Storage="_CHITIETHOADONs", ThisKey="id_hd", OtherKey="id_hd")]
		public EntitySet<CHITIETHOADON> CHITIETHOADONs
		{
			get
			{
				return this._CHITIETHOADONs;
			}
			set
			{
				this._CHITIETHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VOUCHER_HOADON", Storage="_VOUCHER", ThisKey="id_voucher", OtherKey="id_voucher", IsForeignKey=true)]
		public VOUCHER VOUCHER
		{
			get
			{
				return this._VOUCHER.Entity;
			}
			set
			{
				VOUCHER previousValue = this._VOUCHER.Entity;
				if (((previousValue != value) 
							|| (this._VOUCHER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VOUCHER.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._VOUCHER.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._id_voucher = value.id_voucher;
					}
					else
					{
						this._id_voucher = default(Nullable<int>);
					}
					this.SendPropertyChanged("VOUCHER");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_NHANVIEN", ThisKey="id_nv", OtherKey="id_nv", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._id_nv = value.id_nv;
					}
					else
					{
						this._id_nv = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOILUONG")]
	public partial class KHOILUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kl;
		
		private string _tenkhoiluong;
		
		private EntitySet<DINHLUONG> _DINHLUONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klChanging(int value);
    partial void Onid_klChanged();
    partial void OntenkhoiluongChanging(string value);
    partial void OntenkhoiluongChanged();
    #endregion
		
		public KHOILUONG()
		{
			this._DINHLUONGs = new EntitySet<DINHLUONG>(new Action<DINHLUONG>(this.attach_DINHLUONGs), new Action<DINHLUONG>(this.detach_DINHLUONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kl
		{
			get
			{
				return this._id_kl;
			}
			set
			{
				if ((this._id_kl != value))
				{
					this.Onid_klChanging(value);
					this.SendPropertyChanging();
					this._id_kl = value;
					this.SendPropertyChanged("id_kl");
					this.Onid_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhoiluong", DbType="NVarChar(20)")]
		public string tenkhoiluong
		{
			get
			{
				return this._tenkhoiluong;
			}
			set
			{
				if ((this._tenkhoiluong != value))
				{
					this.OntenkhoiluongChanging(value);
					this.SendPropertyChanging();
					this._tenkhoiluong = value;
					this.SendPropertyChanged("tenkhoiluong");
					this.OntenkhoiluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOILUONG_DINHLUONG", Storage="_DINHLUONGs", ThisKey="id_kl", OtherKey="id_kl")]
		public EntitySet<DINHLUONG> DINHLUONGs
		{
			get
			{
				return this._DINHLUONGs;
			}
			set
			{
				this._DINHLUONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DINHLUONGs(DINHLUONG entity)
		{
			this.SendPropertyChanging();
			entity.KHOILUONG = this;
		}
		
		private void detach_DINHLUONGs(DINHLUONG entity)
		{
			this.SendPropertyChanging();
			entity.KHOILUONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI")]
	public partial class LOAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_loai;
		
		private string _tenloai;
		
		private EntitySet<MENU> _MENUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loaiChanging(int value);
    partial void Onid_loaiChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    #endregion
		
		public LOAI()
		{
			this._MENUs = new EntitySet<MENU>(new Action<MENU>(this.attach_MENUs), new Action<MENU>(this.detach_MENUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="NVarChar(100)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_MENU", Storage="_MENUs", ThisKey="id_loai", OtherKey="id_loai")]
		public EntitySet<MENU> MENUs
		{
			get
			{
				return this._MENUs;
			}
			set
			{
				this._MENUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MENUs(MENU entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = this;
		}
		
		private void detach_MENUs(MENU entity)
		{
			this.SendPropertyChanging();
			entity.LOAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU")]
	public partial class MENU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_mon;
		
		private int _id_loai;
		
		private string _tenmon;
		
		private System.Nullable<int> _giaban;
		
		private string _ghichu;
		
		private string _hinh;
		
		private EntitySet<CHITIETDONHANGONLINE> _CHITIETDONHANGONLINEs;
		
		private EntitySet<CHITIETHOADON> _CHITIETHOADONs;
		
		private EntitySet<NGUYENLIEULAMMON> _NGUYENLIEULAMMONs;
		
		private EntityRef<LOAI> _LOAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_monChanging(int value);
    partial void Onid_monChanged();
    partial void Onid_loaiChanging(int value);
    partial void Onid_loaiChanged();
    partial void OntenmonChanging(string value);
    partial void OntenmonChanged();
    partial void OngiabanChanging(System.Nullable<int> value);
    partial void OngiabanChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OnhinhChanging(string value);
    partial void OnhinhChanged();
    #endregion
		
		public MENU()
		{
			this._CHITIETDONHANGONLINEs = new EntitySet<CHITIETDONHANGONLINE>(new Action<CHITIETDONHANGONLINE>(this.attach_CHITIETDONHANGONLINEs), new Action<CHITIETDONHANGONLINE>(this.detach_CHITIETDONHANGONLINEs));
			this._CHITIETHOADONs = new EntitySet<CHITIETHOADON>(new Action<CHITIETHOADON>(this.attach_CHITIETHOADONs), new Action<CHITIETHOADON>(this.detach_CHITIETHOADONs));
			this._NGUYENLIEULAMMONs = new EntitySet<NGUYENLIEULAMMON>(new Action<NGUYENLIEULAMMON>(this.attach_NGUYENLIEULAMMONs), new Action<NGUYENLIEULAMMON>(this.detach_NGUYENLIEULAMMONs));
			this._LOAI = default(EntityRef<LOAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_mon
		{
			get
			{
				return this._id_mon;
			}
			set
			{
				if ((this._id_mon != value))
				{
					this.Onid_monChanging(value);
					this.SendPropertyChanging();
					this._id_mon = value;
					this.SendPropertyChanged("id_mon");
					this.Onid_monChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loai", DbType="Int NOT NULL")]
		public int id_loai
		{
			get
			{
				return this._id_loai;
			}
			set
			{
				if ((this._id_loai != value))
				{
					if (this._LOAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loaiChanging(value);
					this.SendPropertyChanging();
					this._id_loai = value;
					this.SendPropertyChanged("id_loai");
					this.Onid_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenmon", DbType="NVarChar(100)")]
		public string tenmon
		{
			get
			{
				return this._tenmon;
			}
			set
			{
				if ((this._tenmon != value))
				{
					this.OntenmonChanging(value);
					this.SendPropertyChanging();
					this._tenmon = value;
					this.SendPropertyChanged("tenmon");
					this.OntenmonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaban", DbType="Int")]
		public System.Nullable<int> giaban
		{
			get
			{
				return this._giaban;
			}
			set
			{
				if ((this._giaban != value))
				{
					this.OngiabanChanging(value);
					this.SendPropertyChanging();
					this._giaban = value;
					this.SendPropertyChanged("giaban");
					this.OngiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(100)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh", DbType="VarChar(100)")]
		public string hinh
		{
			get
			{
				return this._hinh;
			}
			set
			{
				if ((this._hinh != value))
				{
					this.OnhinhChanging(value);
					this.SendPropertyChanging();
					this._hinh = value;
					this.SendPropertyChanged("hinh");
					this.OnhinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_CHITIETDONHANGONLINE", Storage="_CHITIETDONHANGONLINEs", ThisKey="id_mon", OtherKey="id_mon")]
		public EntitySet<CHITIETDONHANGONLINE> CHITIETDONHANGONLINEs
		{
			get
			{
				return this._CHITIETDONHANGONLINEs;
			}
			set
			{
				this._CHITIETDONHANGONLINEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_CHITIETHOADON", Storage="_CHITIETHOADONs", ThisKey="id_mon", OtherKey="id_mon")]
		public EntitySet<CHITIETHOADON> CHITIETHOADONs
		{
			get
			{
				return this._CHITIETHOADONs;
			}
			set
			{
				this._CHITIETHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_NGUYENLIEULAMMON", Storage="_NGUYENLIEULAMMONs", ThisKey="id_mon", OtherKey="id_mon")]
		public EntitySet<NGUYENLIEULAMMON> NGUYENLIEULAMMONs
		{
			get
			{
				return this._NGUYENLIEULAMMONs;
			}
			set
			{
				this._NGUYENLIEULAMMONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_MENU", Storage="_LOAI", ThisKey="id_loai", OtherKey="id_loai", IsForeignKey=true)]
		public LOAI LOAI
		{
			get
			{
				return this._LOAI.Entity;
			}
			set
			{
				LOAI previousValue = this._LOAI.Entity;
				if (((previousValue != value) 
							|| (this._LOAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI.Entity = null;
						previousValue.MENUs.Remove(this);
					}
					this._LOAI.Entity = value;
					if ((value != null))
					{
						value.MENUs.Add(this);
						this._id_loai = value.id_loai;
					}
					else
					{
						this._id_loai = default(int);
					}
					this.SendPropertyChanged("LOAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONHANGONLINEs(CHITIETDONHANGONLINE entity)
		{
			this.SendPropertyChanging();
			entity.MENU = this;
		}
		
		private void detach_CHITIETDONHANGONLINEs(CHITIETDONHANGONLINE entity)
		{
			this.SendPropertyChanging();
			entity.MENU = null;
		}
		
		private void attach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.MENU = this;
		}
		
		private void detach_CHITIETHOADONs(CHITIETHOADON entity)
		{
			this.SendPropertyChanging();
			entity.MENU = null;
		}
		
		private void attach_NGUYENLIEULAMMONs(NGUYENLIEULAMMON entity)
		{
			this.SendPropertyChanging();
			entity.MENU = this;
		}
		
		private void detach_NGUYENLIEULAMMONs(NGUYENLIEULAMMON entity)
		{
			this.SendPropertyChanging();
			entity.MENU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUYENLIEU")]
	public partial class NGUYENLIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nguyenlieu;
		
		private int _id_ncc;
		
		private string _tennguyenlieu;
		
		private System.Nullable<int> _khoiluongnguyenlieu;
		
		private System.Nullable<int> _gianhap;
		
		private EntitySet<CHITIETDONNHAPHANG> _CHITIETDONNHAPHANGs;
		
		private EntitySet<DINHLUONG> _DINHLUONGs;
		
		private EntitySet<NGUYENLIEULAMMON> _NGUYENLIEULAMMONs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nguyenlieuChanging(int value);
    partial void Onid_nguyenlieuChanged();
    partial void Onid_nccChanging(int value);
    partial void Onid_nccChanged();
    partial void OntennguyenlieuChanging(string value);
    partial void OntennguyenlieuChanged();
    partial void OnkhoiluongnguyenlieuChanging(System.Nullable<int> value);
    partial void OnkhoiluongnguyenlieuChanged();
    partial void OngianhapChanging(System.Nullable<int> value);
    partial void OngianhapChanged();
    #endregion
		
		public NGUYENLIEU()
		{
			this._CHITIETDONNHAPHANGs = new EntitySet<CHITIETDONNHAPHANG>(new Action<CHITIETDONNHAPHANG>(this.attach_CHITIETDONNHAPHANGs), new Action<CHITIETDONNHAPHANG>(this.detach_CHITIETDONNHAPHANGs));
			this._DINHLUONGs = new EntitySet<DINHLUONG>(new Action<DINHLUONG>(this.attach_DINHLUONGs), new Action<DINHLUONG>(this.detach_DINHLUONGs));
			this._NGUYENLIEULAMMONs = new EntitySet<NGUYENLIEULAMMON>(new Action<NGUYENLIEULAMMON>(this.attach_NGUYENLIEULAMMONs), new Action<NGUYENLIEULAMMON>(this.detach_NGUYENLIEULAMMONs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguyenlieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nguyenlieu
		{
			get
			{
				return this._id_nguyenlieu;
			}
			set
			{
				if ((this._id_nguyenlieu != value))
				{
					this.Onid_nguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._id_nguyenlieu = value;
					this.SendPropertyChanged("id_nguyenlieu");
					this.Onid_nguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ncc", DbType="Int NOT NULL")]
		public int id_ncc
		{
			get
			{
				return this._id_ncc;
			}
			set
			{
				if ((this._id_ncc != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nccChanging(value);
					this.SendPropertyChanging();
					this._id_ncc = value;
					this.SendPropertyChanged("id_ncc");
					this.Onid_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennguyenlieu", DbType="NVarChar(100)")]
		public string tennguyenlieu
		{
			get
			{
				return this._tennguyenlieu;
			}
			set
			{
				if ((this._tennguyenlieu != value))
				{
					this.OntennguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._tennguyenlieu = value;
					this.SendPropertyChanged("tennguyenlieu");
					this.OntennguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiluongnguyenlieu", DbType="Int")]
		public System.Nullable<int> khoiluongnguyenlieu
		{
			get
			{
				return this._khoiluongnguyenlieu;
			}
			set
			{
				if ((this._khoiluongnguyenlieu != value))
				{
					this.OnkhoiluongnguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._khoiluongnguyenlieu = value;
					this.SendPropertyChanged("khoiluongnguyenlieu");
					this.OnkhoiluongnguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gianhap", DbType="Int")]
		public System.Nullable<int> gianhap
		{
			get
			{
				return this._gianhap;
			}
			set
			{
				if ((this._gianhap != value))
				{
					this.OngianhapChanging(value);
					this.SendPropertyChanging();
					this._gianhap = value;
					this.SendPropertyChanged("gianhap");
					this.OngianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_CHITIETDONNHAPHANG", Storage="_CHITIETDONNHAPHANGs", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu")]
		public EntitySet<CHITIETDONNHAPHANG> CHITIETDONNHAPHANGs
		{
			get
			{
				return this._CHITIETDONNHAPHANGs;
			}
			set
			{
				this._CHITIETDONNHAPHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_DINHLUONG", Storage="_DINHLUONGs", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu")]
		public EntitySet<DINHLUONG> DINHLUONGs
		{
			get
			{
				return this._DINHLUONGs;
			}
			set
			{
				this._DINHLUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_NGUYENLIEULAMMON", Storage="_NGUYENLIEULAMMONs", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu")]
		public EntitySet<NGUYENLIEULAMMON> NGUYENLIEULAMMONs
		{
			get
			{
				return this._NGUYENLIEULAMMONs;
			}
			set
			{
				this._NGUYENLIEULAMMONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NHACUNGCAP", ThisKey="id_ncc", OtherKey="id_ncc", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.NGUYENLIEUs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEUs.Add(this);
						this._id_ncc = value.id_ncc;
					}
					else
					{
						this._id_ncc = default(int);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETDONNHAPHANGs(CHITIETDONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = this;
		}
		
		private void detach_CHITIETDONNHAPHANGs(CHITIETDONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = null;
		}
		
		private void attach_DINHLUONGs(DINHLUONG entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = this;
		}
		
		private void detach_DINHLUONGs(DINHLUONG entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = null;
		}
		
		private void attach_NGUYENLIEULAMMONs(NGUYENLIEULAMMON entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = this;
		}
		
		private void detach_NGUYENLIEULAMMONs(NGUYENLIEULAMMON entity)
		{
			this.SendPropertyChanging();
			entity.NGUYENLIEU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUYENLIEULAMMON")]
	public partial class NGUYENLIEULAMMON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_mon;
		
		private int _id_nguyenlieu;
		
		private EntityRef<MENU> _MENU;
		
		private EntityRef<NGUYENLIEU> _NGUYENLIEU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_monChanging(int value);
    partial void Onid_monChanged();
    partial void Onid_nguyenlieuChanging(int value);
    partial void Onid_nguyenlieuChanged();
    #endregion
		
		public NGUYENLIEULAMMON()
		{
			this._MENU = default(EntityRef<MENU>);
			this._NGUYENLIEU = default(EntityRef<NGUYENLIEU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_mon
		{
			get
			{
				return this._id_mon;
			}
			set
			{
				if ((this._id_mon != value))
				{
					if (this._MENU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_monChanging(value);
					this.SendPropertyChanging();
					this._id_mon = value;
					this.SendPropertyChanged("id_mon");
					this.Onid_monChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nguyenlieu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nguyenlieu
		{
			get
			{
				return this._id_nguyenlieu;
			}
			set
			{
				if ((this._id_nguyenlieu != value))
				{
					if (this._NGUYENLIEU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nguyenlieuChanging(value);
					this.SendPropertyChanging();
					this._id_nguyenlieu = value;
					this.SendPropertyChanged("id_nguyenlieu");
					this.Onid_nguyenlieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MENU_NGUYENLIEULAMMON", Storage="_MENU", ThisKey="id_mon", OtherKey="id_mon", IsForeignKey=true)]
		public MENU MENU
		{
			get
			{
				return this._MENU.Entity;
			}
			set
			{
				MENU previousValue = this._MENU.Entity;
				if (((previousValue != value) 
							|| (this._MENU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MENU.Entity = null;
						previousValue.NGUYENLIEULAMMONs.Remove(this);
					}
					this._MENU.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEULAMMONs.Add(this);
						this._id_mon = value.id_mon;
					}
					else
					{
						this._id_mon = default(int);
					}
					this.SendPropertyChanged("MENU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUYENLIEU_NGUYENLIEULAMMON", Storage="_NGUYENLIEU", ThisKey="id_nguyenlieu", OtherKey="id_nguyenlieu", IsForeignKey=true)]
		public NGUYENLIEU NGUYENLIEU
		{
			get
			{
				return this._NGUYENLIEU.Entity;
			}
			set
			{
				NGUYENLIEU previousValue = this._NGUYENLIEU.Entity;
				if (((previousValue != value) 
							|| (this._NGUYENLIEU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUYENLIEU.Entity = null;
						previousValue.NGUYENLIEULAMMONs.Remove(this);
					}
					this._NGUYENLIEU.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEULAMMONs.Add(this);
						this._id_nguyenlieu = value.id_nguyenlieu;
					}
					else
					{
						this._id_nguyenlieu = default(int);
					}
					this.SendPropertyChanged("NGUYENLIEU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ncc;
		
		private string _tenncc;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private EntitySet<DONNHAPHANG> _DONNHAPHANGs;
		
		private EntitySet<NGUYENLIEU> _NGUYENLIEUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nccChanging(int value);
    partial void Onid_nccChanged();
    partial void OntennccChanging(string value);
    partial void OntennccChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._DONNHAPHANGs = new EntitySet<DONNHAPHANG>(new Action<DONNHAPHANG>(this.attach_DONNHAPHANGs), new Action<DONNHAPHANG>(this.detach_DONNHAPHANGs));
			this._NGUYENLIEUs = new EntitySet<NGUYENLIEU>(new Action<NGUYENLIEU>(this.attach_NGUYENLIEUs), new Action<NGUYENLIEU>(this.detach_NGUYENLIEUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ncc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ncc
		{
			get
			{
				return this._id_ncc;
			}
			set
			{
				if ((this._id_ncc != value))
				{
					this.Onid_nccChanging(value);
					this.SendPropertyChanging();
					this._id_ncc = value;
					this.SendPropertyChanged("id_ncc");
					this.Onid_nccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenncc", DbType="NVarChar(100)")]
		public string tenncc
		{
			get
			{
				return this._tenncc;
			}
			set
			{
				if ((this._tenncc != value))
				{
					this.OntennccChanging(value);
					this.SendPropertyChanging();
					this._tenncc = value;
					this.SendPropertyChanged("tenncc");
					this.OntennccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_DONNHAPHANG", Storage="_DONNHAPHANGs", ThisKey="id_ncc", OtherKey="id_ncc")]
		public EntitySet<DONNHAPHANG> DONNHAPHANGs
		{
			get
			{
				return this._DONNHAPHANGs;
			}
			set
			{
				this._DONNHAPHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NGUYENLIEUs", ThisKey="id_ncc", OtherKey="id_ncc")]
		public EntitySet<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this._NGUYENLIEUs;
			}
			set
			{
				this._NGUYENLIEUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONNHAPHANGs(DONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_DONNHAPHANGs(DONNHAPHANG entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
		
		private void attach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nv;
		
		private int _id_quyen;
		
		private string _tennv;
		
		private System.Nullable<bool> _tinhtranglamviec;
		
		private string _username;
		
		private string _password;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<PHANQUYEN> _PHANQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nvChanging(int value);
    partial void Onid_nvChanged();
    partial void Onid_quyenChanging(int value);
    partial void Onid_quyenChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OntinhtranglamviecChanging(System.Nullable<bool> value);
    partial void OntinhtranglamviecChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._PHANQUYEN = default(EntityRef<PHANQUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nv", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nv
		{
			get
			{
				return this._id_nv;
			}
			set
			{
				if ((this._id_nv != value))
				{
					this.Onid_nvChanging(value);
					this.SendPropertyChanging();
					this._id_nv = value;
					this.SendPropertyChanged("id_nv");
					this.Onid_nvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_quyen", DbType="Int NOT NULL")]
		public int id_quyen
		{
			get
			{
				return this._id_quyen;
			}
			set
			{
				if ((this._id_quyen != value))
				{
					if (this._PHANQUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_quyenChanging(value);
					this.SendPropertyChanging();
					this._id_quyen = value;
					this.SendPropertyChanged("id_quyen");
					this.Onid_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="NVarChar(50)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtranglamviec", DbType="Bit")]
		public System.Nullable<bool> tinhtranglamviec
		{
			get
			{
				return this._tinhtranglamviec;
			}
			set
			{
				if ((this._tinhtranglamviec != value))
				{
					this.OntinhtranglamviecChanging(value);
					this.SendPropertyChanging();
					this._tinhtranglamviec = value;
					this.SendPropertyChanged("tinhtranglamviec");
					this.OntinhtranglamviecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_HOADONs", ThisKey="id_nv", OtherKey="id_nv")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NHANVIEN", Storage="_PHANQUYEN", ThisKey="id_quyen", OtherKey="id_quyen", IsForeignKey=true)]
		public PHANQUYEN PHANQUYEN
		{
			get
			{
				return this._PHANQUYEN.Entity;
			}
			set
			{
				PHANQUYEN previousValue = this._PHANQUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHANQUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANQUYEN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._PHANQUYEN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._id_quyen = value.id_quyen;
					}
					else
					{
						this._id_quyen = default(int);
					}
					this.SendPropertyChanged("PHANQUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_quyen;
		
		private string _phanquyen1;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_quyenChanging(int value);
    partial void Onid_quyenChanged();
    partial void Onphanquyen1Changing(string value);
    partial void Onphanquyen1Changed();
    #endregion
		
		public PHANQUYEN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_quyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_quyen
		{
			get
			{
				return this._id_quyen;
			}
			set
			{
				if ((this._id_quyen != value))
				{
					this.Onid_quyenChanging(value);
					this.SendPropertyChanging();
					this._id_quyen = value;
					this.SendPropertyChanged("id_quyen");
					this.Onid_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="phanquyen", Storage="_phanquyen1", DbType="NVarChar(50)")]
		public string phanquyen1
		{
			get
			{
				return this._phanquyen1;
			}
			set
			{
				if ((this._phanquyen1 != value))
				{
					this.Onphanquyen1Changing(value);
					this.SendPropertyChanging();
					this._phanquyen1 = value;
					this.SendPropertyChanged("phanquyen1");
					this.Onphanquyen1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANQUYEN_NHANVIEN", Storage="_NHANVIENs", ThisKey="id_quyen", OtherKey="id_quyen")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.PHANQUYEN = null;
		}
	}
}
#pragma warning restore 1591
